version: '3'
services:
  cards-against-humanity:
    image: emcniece/dockeryourxyzzy:4
    restart: always
    ports:
    - "40001:8080"
  pictionary:
    build: pictionary
    restart: always
    ports:
    - "40002:8080"
  battleship:
    build: battleship
    restart: always
    ports:
    - "40003:5000"
  chess:
    build: chess
    restart: always
    ports:
    - "40004:8080"
  catan:
    build: catan
    restart: always
    ports:
    - "40005:4567"
  cards-against-humanity-server:
    image: ghcr.io/lattyware/massivedecks/server@sha256:bd203a244f504d868e7355db33634b1312e5a954dd12fa4435665ce847b840f5
    restart: always
    networks:
    - cards-against-humanity
  cards-against-humanity-client:
    image: ghcr.io/lattyware/massivedecks/client@sha256:45b2e99a3aa68923a2a541e5954a0d52d31f93b1f318e594aaf9ca116e2ebae1
    restart: always
    networks:
    - cards-against-humanity
    links:
      - "cards-against-humanity-server:server"
    depends_on:
      - cards-against-humanity-server
    ports:
    - "40006:8080"
  spyfall:
    build: spyfall
    restart: always
    ports:
    - "40007:3000"
  #agar-io:
  #  build: agar-io
  #  restart: always
  #  ports:
  #  - "40008:3000"
  agar-io-cigar:
    build:
      context: agar-io/cigar
      args:
        OGAR_SERVER: "api.agar-io.games.fachschaften.org"
    restart: always
    depends_on:
      - agar-io-ogar
    ports:
    - "40009:3000"
  agar-io-ogar:
    build: agar-io/ogar
    restart: always
    ports:
    - "40010:443"
  kung-fu-chess:
    build: kung-fu-chess
    restart: always
    ports:
    - "40011:8080"
  codenames:
    build: codenames
    restart: always
    ports:
    - "40012:9091"
  werewolf:
    build: werewolf
    restart: always
    ports:
    - "40013:5000"

networks:
  cards-against-humanity:
