version: '3'
services:
  cards-against-humanity:
    image: emcniece/dockeryourxyzzy:4
    restart: always
    ports:
    - "40001:8080"
  pictionary:
    build: pictionary
    restart: always
    ports:
    - "40002:8080"
  battleship:
    build: battleship
    restart: always
    ports:
    - "40003:5000"
  chess:
    build: chess
    restart: always
    ports:
    - "40004:8080"
  catan:
    build: catan
    restart: always
    ports:
    - "40005:4567"
  cards-against-humanity-server:
    image: ghcr.io/lattyware/massivedecks/server@sha256:052fd00924b982d7a8b272d1d2ac7f788c57cd9feedf8ef67cc0a179e17a67ce
    restart: always
    networks:
    - cards-against-humanity
  cards-against-humanity-client:
    image: ghcr.io/lattyware/massivedecks/client@sha256:83f69ae4afb2cc183c131e603a79f8903514520aba90d69d657e643788934562
    restart: always
    networks:
    - cards-against-humanity
    links:
      - "cards-against-humanity-server:server"
    depends_on:
      - cards-against-humanity-server
    ports:
    - "40006:8080"
  spyfall:
    build: spyfall
    restart: always
    ports:
    - "40007:3000"
  agar-io:
    build: agar-io
    restart: always
    ports:
    - "40008:3000"
  agar-io-cigar:
    build:
      context: agar-io/cigar
      args:
        OGAR_SERVER: "localhost:40010"
    restart: always
    depends_on:
      - agar-io-ogar
    ports:
    - "40009:3000"
  agar-io-ogar:
    build: agar-io/ogar
    restart: always
    ports:
    - "40010:443"
  kung-fu-chess:
    build: kung-fu-chess
    restart: always
    ports:
    - "40011:8080"
#  codenames:
#    build: codenames
#    restart: always
#    ports:
#    - "4000x:8080"
#  fake-artist:
#    build: fake-artist
#    restart: always
#    ports:
#    - "4000x:8080"

networks:
  cards-against-humanity:
