version: '3'
services:
  cards-against-humanity:
    build: cards-against-humanity
    restart: always
    ports:
    - "40001:8080"
  pictionary:
    build: pictionary
    restart: always
    ports:
    - "40002:8080"
